### ISSUE TITLE
load_and_test issues

### ISSUE THREAD

**Issue by xiexuliunian** [tangyuhao/GOTURN-Tensorflow#1]
Hello,In your load_and_test.py there is a " f = open('pkl/right_order_goturn_weights.pkl', 'rb')",but there isn't that file ....I want some help

**Comment by tangyuhao** [comment]
Thanks for pointing out that. Updated, now it should work. "pkl/right_order_goturn_weights.pkl" is the old form of GOTURN weights, I have moved them to checkpoints.
