### ISSUE TITLE
merged_summary and train_writer not defined in train.py

### ISSUE THREAD

**Issue by nuitvolgit** [tangyuhao/GOTURN-Tensorflow#5]
Hello,

I appreciate this open code for GOTURN.
By the way, merged_summary and train_writer have not defined in train.py

One more thing. Line 135 in train.py
"if (i - start > 1000):"
The variable 'i' is not clearly defined.

Please check them out.
Thank you.

**Comment by tangyuhao** [comment]
for the question in train.py, the i means the total iterations since you trained it first time. This train file can be run several times and it will continue train using the last saved checkpoint.

**Comment by tangyuhao** [comment]
For others I need to take a look whether it is the wrong version. Sorry for that.

**Comment by tangyuhao** [comment]
should be fixed now.
